package soporte.hibernate.model;
// Generated 4/08/2013 09:37:15 AM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Etiquetas generated by hbm2java
 */
@Entity
@Table(name="etiquetas"
    ,catalog="soporte"
)
public class Etiquetas  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private Set<Usuarios> usuarioses = new HashSet<Usuarios>(0);

    public Etiquetas() {
    }

	
    public Etiquetas(String nombre) {
        this.nombre = nombre;
    }
    public Etiquetas(int id, String nombre) {
        this.id = id;
        this.nombre = nombre;
    }
    public Etiquetas(String nombre, Set<Usuarios> usuarioses) {
       this.nombre = nombre;
       this.usuarioses = usuarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    @Column(name="nombre", nullable=false, length=40)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
@ManyToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY)
    @JoinTable(name="usuariosetiquetas", catalog="soporte", joinColumns = { 
        @JoinColumn(name="idEtiqueta", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="idUsuario", nullable=false, updatable=false) })
    public Set<Usuarios> getUsuarioses() {
        return this.usuarioses;
    }
    
    public void setUsuarioses(Set<Usuarios> usuarioses) {
        this.usuarioses = usuarioses;
    }




}


