package soporte.hibernate.model;
// Generated 4/08/2013 09:37:15 AM by Hibernate Tools 3.2.1.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Puntuacion generated by hbm2java
 */
@Entity
@Table(name="puntuacion"
    ,catalog="soporte"
)
public class Puntuacion  implements java.io.Serializable {


     private Integer id;
     private Usuarios usuariosByIdUsuarioOrigen;
     private Usuarios usuariosByIdUsuarioDestino;
     private float puntos;
     private String comentario;
     private Character estatus;

    public Puntuacion() {
    }

	
    public Puntuacion(Usuarios usuariosByIdUsuarioOrigen, Usuarios usuariosByIdUsuarioDestino, float puntos) {
        this.usuariosByIdUsuarioOrigen = usuariosByIdUsuarioOrigen;
        this.usuariosByIdUsuarioDestino = usuariosByIdUsuarioDestino;
        this.puntos = puntos;
    }
    public Puntuacion(int id, Usuarios usuariosByIdUsuarioOrigen, Usuarios usuariosByIdUsuarioDestino, float puntos) {
        this.id = id;
        this.usuariosByIdUsuarioOrigen = usuariosByIdUsuarioOrigen;
        this.usuariosByIdUsuarioDestino = usuariosByIdUsuarioDestino;
        this.puntos = puntos;
    }
    public Puntuacion(Usuarios usuariosByIdUsuarioOrigen, Usuarios usuariosByIdUsuarioDestino, float puntos, String comentario, Character estatus) {
       this.usuariosByIdUsuarioOrigen = usuariosByIdUsuarioOrigen;
       this.usuariosByIdUsuarioDestino = usuariosByIdUsuarioDestino;
       this.puntos = puntos;
       this.comentario = comentario;
       this.estatus = estatus;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuarioOrigen", nullable=false)
    public Usuarios getUsuariosByIdUsuarioOrigen() {
        return this.usuariosByIdUsuarioOrigen;
    }
    
    public void setUsuariosByIdUsuarioOrigen(Usuarios usuariosByIdUsuarioOrigen) {
        this.usuariosByIdUsuarioOrigen = usuariosByIdUsuarioOrigen;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idUsuarioDestino", nullable=false)
    public Usuarios getUsuariosByIdUsuarioDestino() {
        return this.usuariosByIdUsuarioDestino;
    }
    
    public void setUsuariosByIdUsuarioDestino(Usuarios usuariosByIdUsuarioDestino) {
        this.usuariosByIdUsuarioDestino = usuariosByIdUsuarioDestino;
    }
    
    @Column(name="puntos", nullable=false, precision=12, scale=0)
    public float getPuntos() {
        return this.puntos;
    }
    
    public void setPuntos(float puntos) {
        this.puntos = puntos;
    }
    
    @Column(name="comentario", length=140)
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    
    @Column(name="estatus", length=1)
    public Character getEstatus() {
        return this.estatus;
    }
    
    public void setEstatus(Character estatus) {
        this.estatus = estatus;
    }




}


